#!/bin/sh

ps -ef | grep $1 | grep -v grep | grep -v killall.sh

for pid in `ps -ef | grep $1 | grep -v grep | grep -v killall.sh | awk '{print $2}'`
do
  printf "Matando processo $pid ... \n"
  kill -9 $pid
done
