#!/bin/bash

ps -ef | grep $1 | grep -v grep | grep -v killer

for pid in `ps -ef | grep $1 | grep -v grep | grep -v killer | awk '{print $2}'`
do
  printf "Matando processo $pid ... \n"
  kill -9 $pid
done
